### ISSUE TITLE
Using WINDOWS_VM_IP as 0.0.0.0 gives false sense to most of the people.

### ISSUE THREAD

**Issue by ajinabraham** [DominikSchlecht/Mobile-Security-Framework-MobSF#12]
https://github.com/DominikSchlecht/Mobile-Security-Framework-MobSF/blob/master/MobSF/settings.py#L340

Why don't you set it to `None` ?
`0.0.0.0` will give a false sense that it is publicly exposed to most of the people.

**Comment by sn0b4ll** [comment]
Yep right, will implement this tomorrow.

**Comment by sn0b4ll** [comment]
Fixed with 0694777.

**Comment by ajinabraham** [comment]
Can you send a PR.

**Comment by sn0b4ll** [comment]
I will fix the binskim issue first and issue an pr this evening.
